package gamelibs;

@:native ("SpriteSheetWrapper")
extern class SpriteSheetWrapper {
	/**
	 * The SpriteSheet wrapper provides an easy way to use spriteSheets generated by Zoe
	 * which don't include path information, with a system that requires images to be in a
	 * subfolder. Simply use SpriteSheetWrapper instead of SpriteSheet, and pass in
	 * a relative path reference, and the image paths will be adjusted.
	 * @class SpriteSheetWrapper
	 * @param {Object} data SpriteSheet data
	 * @param {String} suffix The path relative to the game source. Something like "images/".
	 * @return {SpriteSheet} A SpriteSheet with adjusted paths.
	 * @constructor
	 */
	public function new (data:Dynamic, suffix:String):Void;

}